# SOURCE: https://cloud.google.com/kubernetes-engine/docs/tutorials/guestbook
apiVersion: v1
kind: Service
metadata:
  name: book-service
  labels:
    app: books
    role: cluster-member
    tier: backend
spec:
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app: books
    role: cluster-member
    tier: backend