# SOURCE: https://cloud.google.com/kubernetes-engine/docs/tutorials/guestbook
apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-mgmt
  labels:
    app: books
    role: cluster-member
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: books
  template:
    metadata:
      labels:
        app: books
        role: cluster-member
        tier: backend
    spec:
      containers:
      - name: books-svc
        image: "local/alexandria-books:1.0.001"
        env:
        - name: PORT
          value: "9000"
        - name: SERVICE_NAME
          value: "alexandria-books"
        ports:
        - containerPort: 9000