apiVersion: v1
kind: Service
metadata:
  name: catalogs-service
  labels:
    app: catalogs
    role: cluster-member
    tier: backend
spec:
  ports:
  - port: 9002
    targetPort: 9000
  selector:
    app: catalogs
    role: cluster-member
    tier: backend