# SOURCE: https://cloud.google.com/kubernetes-engine/docs/tutorials/guestbook
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongo
    role: cluster-member
    tier: backend
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongo
    role: cluster-member
    tier: backend