# SOURCE: https://cloud.google.com/kubernetes-engine/docs/tutorials/guestbook
apiVersion: v1
kind: Service
metadata:
  name: users-service
  labels:
    app: users
    role: cluster-member
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 9001
  selector:
    app: users
    role: cluster-member
    tier: backend